/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Layer } from "./components/type";
export { Layer } from "./components/type";
export namespace Components {
    interface ImageCanvas {
        /**
          * Canvas fillStroke
         */
        "canvasFillStyle": string;
        /**
          * Height number
         */
        "height": number;
        /**
          * canvas.content
         */
        "layers": Layer[];
        /**
          * Width number
         */
        "width": number;
    }
}
declare global {
    interface HTMLImageCanvasElement extends Components.ImageCanvas, HTMLStencilElement {
    }
    var HTMLImageCanvasElement: {
        prototype: HTMLImageCanvasElement;
        new (): HTMLImageCanvasElement;
    };
    interface HTMLElementTagNameMap {
        "image-canvas": HTMLImageCanvasElement;
    }
}
declare namespace LocalJSX {
    interface ImageCanvas {
        /**
          * Canvas fillStroke
         */
        "canvasFillStyle"?: string;
        /**
          * Height number
         */
        "height": number;
        /**
          * canvas.content
         */
        "layers"?: Layer[];
        /**
          * Width number
         */
        "width": number;
    }
    interface IntrinsicElements {
        "image-canvas": ImageCanvas;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "image-canvas": LocalJSX.ImageCanvas & JSXBase.HTMLAttributes<HTMLImageCanvasElement>;
        }
    }
}
